# <span style="color:red"> DATASCI 151 - Practice Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

- Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED </span>

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [1]:
print("I will abide by Emory's code of conduct.")

I will abide by Emory's code of conduct.

In [2]:
# import necessary libraries here
import pandas as pd
import numpy as np

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories.

$\qquad$ ``` ["1941-1967","1968-2003","2004-onwards"] ```

- You must use the `pd.cut` function to recode this variable.

- Print the DataFrame to the screen to check your answers

In [3]:
# your code here
df_movies = pd.read_csv("quiz_data/movies.csv")

period_bins = [1941, 1968, 2004, np.inf]
period_labels = ["1941-1967", "1968-2003", "2004-onwards"]
df_movies["time_period"] = pd.cut(df_movies["year"], 
                                bins = period_bins,
                                right = False,
                                labels = period_labels)

display(df_movies)

,title,country,runtime(minutes),year,imdb_score,time_period
0,Past Lives,American,106,2023,7.8,2004-onwards
1,Citizen Kane,American,119,1941,8.2,1941-1967
2,Revenge,France,108,2017,6.4,2004-onwards
3,Okja,Korean,120,2017,7.3,2004-onwards
4,Shutter,Thailand,97,2004,7.0,2004-onwards
5,A Tale of Two Sisters,Korean,115,2003,7.1,1968-2003
6,La Chinoise,France,96,1967,6.9,1941-1967
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
8,House,Japan,88,1977,7.2,1968-2003
9,Suspiria,Italy,98,1977,7.3,1968-2003
10,Blue Velvet,American,120,1986,7.7,1968-2003

<font size = "4">

**Q2** Aggregate and Sort

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Group the data by "country"
    
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score

    - Sort by average IMDB score in **descending order**

- Print the resulting DataFrame to the screen

**Note:** A "single line of code" can continue on to the next line if you use a backslash or wrap the line within a pair of parentheses.

In [4]:
# your code here
display(df_movies.groupby('country').agg(avg_runtime = ('runtime(minutes)', 'mean'), max_runtime = ('runtime(minutes)', 'max'), 
                                 avg_imdb = ('imdb_score', 'mean'), min_imdb = ('imdb_score', 'min')).sort_values(by = 'avg_imdb', ascending = False))

          avg_runtime  max_runtime  avg_imdb  min_imdb
country
American   115.000000          120  7.900000       7.7
Italy       98.000000           98  7.300000       7.3
Japan       88.000000           88  7.200000       7.2
Korean     117.500000          120  7.200000       7.1
France      98.333333          108  7.033333       6.4
Thailand    97.000000           97  7.000000       7.0

<font size = "4">

**Q3** Subsetting data

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Subset the observations for 'country == "France" using ```.query()```

    - Sort the values by year (oldest first)

    - Extract the two oldest movies

In [5]:
# your code here
display(df_movies.query('country == "France"').sort_values(by = "year", ascending = True).head(2))

,title,country,runtime(minutes),year,imdb_score,time_period
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
6,La Chinoise,France,96,1967,6.9,1941-1967

<font size = "4">

**Q4** Aggregate and query

<font size = "3">

- Read in the file "sprint_results.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Do the following in a single line using chaining:

    - Extract the subset with constructorId equal to 51.

    - Aggregate the maximum number of laps and average number of laps for each driver in the subset.

    - Extract the subset of these drivers with maximum # of laps $\geq 20$.

In [15]:
# your code here
df_sprint = pd.read_csv("quiz_data/sprint_results.csv")
display(df_sprint.query('constructorId == 51').groupby("driverId").agg(maxlap = ('laps', 'max'), avglaps = ('laps', 'mean')).query('maxlap >= 20'))

          maxlap    avglaps
driverId
8             24  20.500000
822           23  22.000000
841           24  19.666667
855           23  11.500000

<font size = "4">

**Q5** Calculate race duration

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $6 \times 10^{-4}$

- Group the data by **both** "raceId" and "constructorId" and calculate the average race duration in minutes for each group.

- Sort the data in descending order and then extract the raceId/constructorId pairs with the 5 slowest average times.

In [17]:
# your code here
df_results_clean = pd.read_csv("quiz_data/results_cleaned.csv")
df_results_clean["race_duration_minutes"] = df_results_clean["milliseconds"] / 60000
df_results_clean.groupby(["raceId", "constructorId"])["race_duration_minutes"].mean().sort_values(ascending=False).head(5)

raceId  constructorId
818     129              251.509000
        107              248.783000
847     15               245.466258
        3                245.410900
        5                245.350783
Name: race_duration_minutes, dtype: float64

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv".

- When a driver finishes 1st, 2nd, or 3rd it is known as a "podium finish". Write a function that takes in a Pandas Series and returns the number of entries $\leq 3$.

- Group by "driverId" and then aggregate the following statistics: the average of the "points" column, and the number of podium finishes in the "positionOrder" column - use your custom function for this second statistic.

- Merge the aggregated data back into the original DataFrame.

In [20]:
# your code here
def podnum(list):
    n = 0
    for i in list:
        if i <= 3:
            n = n + 1
    return n

display(df_results_clean.groupby("driverId").agg(Avg_Points = ('points', 'mean'), Num_Podiums = ('positionOrder', podnum)).merge(df_results_clean, on = "driverId"))

,driverId,Avg_Points,Num_Podiums,resultId,raceId,constructorId,number,grid,position,positionText,...,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,race_duration_minutes
0,1,14.313953,188,1,18,1,22,1,1,1,...,10.0,58,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1,94.843600
1,1,14.313953,188,27,19,1,22,9,5,5,...,4.0,56,+46.548,5525103.0,53,3,1:35.462,209.033,1,92.085050
2,1,14.313953,188,57,20,1,22,3,13,13,...,0.0,56,\N,NaN,25,19,1:35.520,203.969,11,NaN
3,1,14.313953,188,69,21,1,22,5,3,3,...,6.0,66,+4.187,5903238.0,20,3,1:22.017,204.323,1,98.387300
4,1,14.313953,188,90,22,1,22,3,2,2,...,8.0,58,+3.779,5213230.0,31,2,1:26.529,222.085,1,86.887167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,855,0.384615,0,25573,1082,51,24,10,8,8,...,4.0,70,+26.952,5808709.0,60,7,1:16.927,204.084,1,96.811817
25656,855,0.384615,0,25604,1083,51,24,9,\N,R,...,0.0,0,\N,NaN,\N,0,\N,\N,4,NaN
25657,855,0.384615,0,25619,1084,51,24,13,14,14,...,0.0,70,\N,NaN,50,9,1:09.380,224.053,11,NaN
25658,855,0.384615,0,25641,1085,51,24,16,16,16,...,0.0,47,\N,NaN,25,18,1:39.368,211.649,16,NaN
25659,855,0.384615,0,25658,1086,51,24,12,13,13,...,0.0,69,\N,NaN,58,5,1:22.029,192.268,11,NaN